/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as IndexRouteImport } from './routes/index'

const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o-nas': typeof ONasRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/o-nas' | '/polityka-prywatnosci'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/o-nas' | '/polityka-prywatnosci'
  id: '__root__' | '/' | '/o-nas' | '/polityka-prywatnosci'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ONasRoute: typeof ONasRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ONasRoute: ONasRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
